function [result] = crc16(data, crc16tab)
    result = 0x0000;
    data = uint64(data);
    buf = zeros(8, 1);
    for i = 8:-1:1
        shiftdist = 8 * (i - 1);
        mask = bitshift(0x00000000000000FF, shiftdist);
        buf(i) = uint8(bitshift( bitand(data, mask), -shiftdist ));
    end
    for i = 1:8
        block = uint16(buf(i));
        tabidx = bitand( ...
            bitxor( ...
                bitshift(result, -8), ...
                block ...
            ), ...
            0x00FF ...
        );
        tabidx = tabidx + 1;
        result = bitxor( ...
            bitshift(result, 8), ...
            crc16tab( tabidx ) ...
        );
    end
end