function [allocation] = getElasticHeuristicAllocation( ...
    constrLB, ...
    constrUB, ...
    constrMinSep, ...
    currentAlloc, ...
    maxIter, ...
    earlyTermination, ...
    constrOpt ...
)

    NUM_STAGES = 20;

    numAccesses = length(constrUB);
    A = zeros(numAccesses);
    A(1, 1) = 1;
    for r = 2:numAccesses
        A(r, r - 1) = -1;
        A(r, r) = 1;
    end
    A = -A;
    constrMinSep = -constrMinSep;

    % Objective: minimize overlap (maximize utilization).
%     function [c, ceq] = f2(x)
%         c = sum(currentAlloc(x)) - 1;
%         ceq = [];
%     end
%     currX = find(currentAlloc);
%     function [y] = f1(x)
%         fx = [x currX'];
%         y = -length(unique(fx));
%     end

%     f = @(x) [ sum(currentAlloc(x)); -length(unique(x)) ];

    f = @(x) (1 + sum(currentAlloc(x))) / (100 * length(unique(x)));

    if earlyTermination
        options = optimoptions( ...
            'surrogateopt', ...
            'PlotFcn', 'surrogateoptplot', ...
            'MaxFunctionEvaluations', maxIter, ...
            'ObjectiveLimit', 1 ...
        );
    else
        options = optimoptions( ...
            'surrogateopt', ...
            'PlotFcn', 'surrogateoptplot', ...
            'MaxFunctionEvaluations', maxIter ...
        );
    end

    x = surrogateopt( ...
        f, ...
        constrLB, ...
        constrUB, ...
        1:numAccesses, ...
        A, constrMinSep, ...
        [], [], ...
        options ...
    );
%     x = ga( ...
%         @f1, ...
%         numAccesses, ...
%         A, constrMinSep, ...
%         [], [], ...
%         constrLB, constrUB, ...
%         @f2, ...
%         1:numAccesses ...
%     );
%     x = gamultiobj( ...
%         f, ...
%         numAccesses, ...
%         A, constrMinSep, ...
%         [], [], ...
%         constrLB, constrUB, ...
%         [], ...
%         1:numAccesses ...
%     );
    
    conflicts = find(currentAlloc(x));
    conflicts = intersect(conflicts, x(constrOpt));
    x = setdiff(x, conflicts);
    x = unique(x);
    allocation = zeros(NUM_STAGES, 1);
    allocation(x) = 1;
end